name: pigeon_demo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.1
  riverpod_annotation: ^2.0.1

dev_dependencies:
  build_runner: ^2.3.3
  custom_lint: ^0.3.3
  flutter_test:
    sdk: flutter
  pedantic_mono: ^1.21.1
  pigeon: ^9.2.4
  riverpod_generator: ^2.1.6
  riverpod_lint: ^1.2.0

flutter:
  uses-material-design: true
